import dynamic from 'next/dynamic'
import Head from 'next/head'
import { Fragment } from 'react'

const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const ErrorComp = dynamic(() => import('@/Component/Error/ErrorComp'))

function Error() {
  return (
    <Fragment>
      <Head>
        <title>Aquariun - 404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        <ErrorComp />
        <Footer />
      </main>
    </Fragment>
  )
}

export default Error