import LoginError from '@/Component/Error/LoginError'
import Loading from '@/Component/Loading/Loading'
import { userAxios } from '@/Config/Server'
import ContentControl from '@/ContentControl/ContentControl'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Fragment, useContext, useState, useEffect } from 'react'
const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const AddressComp = dynamic(() => import('@/Component/User/Address/AddressComp'), {
    ssr: false
})

export default function Address() {
    const { userLogged, setLoginModal, setUserLogged } = useContext(ContentControl)

    const router = useRouter()

    const [update, setUpdate] = useState(false)

    const [logError, setLogError] = useState(false)

    const [loaded, setLoaded] = useState(false)

    const [address, setAddress] = useState({})

    useEffect(() => {
        const token = localStorage.getItem('token')
        setLogError(false)
        if (token) {
            userAxios((server) => {
                server.get('/users/getAllAddress').then((res) => {
                    if (res.data.login) {
                        setUserLogged({ status: false })
                        localStorage.removeItem('token')
                        setLoaded(true)
                        setLogError(true)
                        setLoginModal(loginModal => ({
                            ...loginModal,
                            btn: true,
                            member: true,
                            active: true
                        }))
                    } else {
                        setLoaded(true)
                        setLogError(false)
                        setAddress(res.data)
                    }
                }).catch(() => {
                    setLoaded(true)
                    router.push('/error')
                })
            })
        } else {
            setLoaded(true)
            setLogError(true)
            setLoginModal(loginModal => ({
                ...loginModal,
                btn: true,
                member: true,
                active: true
            }))
        }

    }, [userLogged, update])
    return (
        <Fragment>
            <Head>
                <title>Aquariun - Address</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                {
                    loaded ? (
                        <>
                            <Header />
                            {
                                logError ? <LoginError />
                                    : <AddressComp address={address} setUpdate={setUpdate} />
                            }
                            <Footer />
                        </>
                    ) : <Loading />
                }
            </main>
        </Fragment>
    )
}
