import Head from "next/head"
import { Fragment, useContext, useEffect, useState } from "react"
import dynamic from "next/dynamic"
import ContentControl from "@/ContentControl/ContentControl"
import { userAxios } from "@/Config/Server"
import LoginError from "@/Component/Error/LoginError"
import Loading from "@/Component/Loading/Loading"
const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const CartComp = dynamic(() => import('@/Component/User/Cart/CartComp'))

function Cart() {
    const { userLogged, setUserLogged,
        setLoginModal, setCartTotal, setOrderType
    } = useContext(ContentControl)

    const [loaded, setLoaded] = useState(false)
    const [logError, setLogError] = useState(false)
    const [update, setUpdate] = useState(false)

    const [products, setProducts] = useState([])
    const [amount, setAmount] = useState({})

    useEffect(() => {
        const token = localStorage.getItem('token')
        setLogError(false)
        if (token) {
            userAxios((server) => {
                server.get(`/users/getCartItems`).then((res) => {
                    if (res.data.login) {
                        setUserLogged({ status: false })
                        localStorage.removeItem('token')
                        setLogError(true)
                        setLoaded(true)
                        setLoginModal(loginModal => ({
                            ...loginModal,
                            btn: true,
                            member: true,
                            forgot: false,
                            active: true
                        }))
                    } else {
                        setAmount(res.data.amount)
                        setCartTotal(res.data.amount.totalPrice)
                        setProducts(res.data.result)
                        setLoaded(true)
                    }
                }).catch((err) => {
                    console.log(err)
                    alert("Sorry for facing error")
                    setLoaded(true)
                })
            })
        } else {
            setLogError(true)
            setLoaded(true)
            setLoginModal(loginModal => ({
                ...loginModal,
                btn: true,
                member: true,
                forgot: false,
                active: true
            }))
        }
    }, [update, userLogged])

    return (
        <Fragment>
            <Head>
                <title>Aquariun - Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                {
                    loaded ? (
                        <>
                            <Header />
                            {
                                logError ? <LoginError />
                                    : <CartComp
                                        setUpdate={setUpdate}
                                        products={products}
                                        amount={amount}
                                        setOrderType={setOrderType}
                                    />
                            }
                            <Footer />
                        </>
                    ) : <Loading />
                }
            </main>
        </Fragment>
    )
}

export default Cart