import Head from "next/head"
import { Fragment } from "react"
import dynamic from "next/dynamic"
import Server from "@/Config/Server"
const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const Categories = dynamic(() => import('@/Component/User/Categories/CategoriesComp'))

export const getServerSideProps = async () => {
    let categories = await Server.get('/users/getAllCategories').catch(() => {

    })

    return {
        props: {
            categories: categories['data']
        }
    }
}

function categories({ categories }) {
    return (
        <Fragment>
            <Head>
                <title>Aquariun - Categories</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <Header />
                <Categories categories={categories} />
                <Footer />
            </main>
        </Fragment>
    )
}

export default categories