import Server from '@/Config/Server'
import ContentControl from '@/ContentControl/ContentControl'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { Fragment, useContext, useState } from 'react'
import QuickView from '@/Component/User/QuickView/QuickView'
const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const HomePost = dynamic(() => import('@/Component/User/HomePost/HomePost'))
const Slider = dynamic(() => import('@/Component/User/Slider/Slider'))

export async function getServerSideProps() {
  try {

    let layout = await Server.get('/users/getLayouts')

    if (layout.data.sliderOne === null) {
      layout.data.sliderOne = []
    }

    if (layout.data.sliderTwo === null) {
      layout.data.sliderTwo = []
    }

    if (layout.data.banner === null) {
      layout.data.banner = []
    }

    return {
      props: {
        response: layout['data']
      }
    }
  } catch (err) {
    console.log(`Facing An Error ${err}`)
    return {
      redirect: {
        destination: '/404',
        permanent: false,
      },
    }
  }

}

export default function Home({ response }) {
  const { QuickVw } = useContext(ContentControl)

  const [layout, setLayout] = useState(response)
  return (
    <Fragment>
      <Head>
        <title>Aquariun - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Header />
        {QuickVw.active && <QuickView />}
        <Slider layout={layout} />
        <HomePost layout={layout} />
        <Footer />
      </main>
    </Fragment>
  )
}
