import Head from "next/head"
import { Fragment, useContext, useEffect, useState } from "react"
import dynamic from "next/dynamic"
import ContentControl from "@/ContentControl/ContentControl"
import { useRouter } from "next/router"
import Loading from "@/Component/Loading/Loading"
const Footer = dynamic(() => import('@/Component/User/Footer/Footer'))
const Header = dynamic(() => import('@/Component/User/Header/Header'))
const OrderSuccess = dynamic(() => import('@/Component/User/OrderMsg/OrderSuccess'))

function Msg() {
    const { OrderType } = useContext(ContentControl)
    const [loaded, setLoaded] = useState(false)
    const navigate = useRouter()

    useEffect(() => {
        if (!OrderType.exAction) {
            navigate.push('/')
            setLoaded(true)
        } else {
            setLoaded(true)
        }
    }, [])

    return (
        <Fragment>
            <Head>
                <title>Aquariun - Order Success</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                {
                    loaded ? (
                        <>
                            <Header />
                            <OrderSuccess />
                            <Footer />
                        </>
                    ) : <Loading />
                }
            </main>
        </Fragment>
    )
}

export default Msg